name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      matrix:
        node-version: [12.x]

    env:
      CI: true

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install and build
        run: |
          npm i
          npm run build

      - name: Code check
        run: |
          npm run typecheck
          npm run lint:styles
          npm run lint:scripts
          npm run test:coverage -- --runInBand

      - name: Release
        run: npx semantic-release -e ./config/release.config.js
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
